### ISSUE TITLE
Le service ne se crée pas

### ISSUE THREAD

**Issue by WorldOfGZ** [NextDom/plugin-PulseAudio#21]
## Description
Bonjour, j'ai un soucis à la création du service.
pulseaudio_create :
`Create/Update Service Name : speakerhall Address : 11:75:58:34:99:08
/usr/bin/sudo: /usr/bin/sudo: cannot execute binary file`

Le service ne se crée pas, ni le fichier dans init.d

Mon jeedom tourne sur RPI3 et Raspbian stretch. Il est à jour.
L'enceinte est appairée (via l'assistant) et le test son fonctionne

## Etapes à reproduire (pour les bugs)

1. Création d'une enceinte
2. Sauvegarde de l'objet

## Proposition de solution (optionnel):
no idea...

## Environnement:

* **Version Jeedom**: 3.11
* **Plateforme**: rpi3
* **Version du Plugin**: branche master de ce dépot

**Comment by WorldOfGZ** [comment]
Bonjour
Juste pour compléter mon précédent message parce que j'ai solutionné mon problème en modifiant 2 fichiers. A voir si ce que j'ai fait à d'autres issues, mais pour le moment, j'ai fait quelques démarrage et l'enceinte se connecte à chaque démarrage.

Dans **PulseAudio.class.php**, j'ai supprimé pour chaque $cmd le début d'instruction ` '/bin/bash ' .`
Ca a réglé le problème de création du service.

Mais ça a généré un autre soucis (lié ?). J'ai du ajouter le chemin absolu dans 3rdparty/pulseaudio-speaker-service pour les commandes bluetooth-connect.sh et bluetooth-disconnect.sh

**Comment by slobberbone** [comment]
Merci pour la remontée ! Quel OS utilises-tu ?

**Comment by WorldOfGZ** [comment]
C'est Raspbian stretch avec les dernières update

Le lun. 6 août 2018 à 12:56, Slobberbone <notifications@github.com> a
écrit :
