### ISSUE TITLE
Passer les repos au standard PSR-2

### ISSUE THREAD

**Issue by cyrilphoenix71** [NextDom/plugin-PulseAudio#9]
Nettoyer le code en respactant le standard PSR-2 et en suivant : https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra/wiki/Bonnes-pratiques-pour-les-plugins

**Comment by slobberbone** [comment]
Fait : 19e8c194adf5cddbabb244d2f46cec57547bb803
